// Token config - CoinGecko IDs untuk harga real-time
const TOKENS = {
  // Stablecoins (harga selalu ~$1, tapi tetap fetch buat akurasi)
  USDC:  { id: 'usd-coin',        symbol: 'USDC', decimals: 6,  type: 'stable' },
  USDT:  { id: 'tether',          symbol: 'USDT', decimals: 6,  type: 'stable' },
  DAI:   { id: 'dai',             symbol: 'DAI',  decimals: 18, type: 'stable' },
  PYUSD: { id: 'paypal-usd',      symbol: 'PYUSD',decimals: 6,  type: 'stable' },
  FRAX:  { id: 'frax',            symbol: 'FRAX', decimals: 18, type: 'stable' },
  USDS:  { id: 'usds',            symbol: 'USDS', decimals: 6,  type: 'stable' },
  TUSD:  { id: 'true-usd',        symbol: 'TUSD', decimals: 18, type: 'stable' },
  BUSD:  { id: 'binance-usd',     symbol: 'BUSD', decimals: 18, type: 'stable' },
  GUSD:  { id: 'gemini-dollar',   symbol: 'GUSD', decimals: 2,  type: 'stable' },
  USDP:  { id: 'pax-dollar',      symbol: 'USDP', decimals: 18, type: 'stable' },

  // Volatile - Solana ecosystem
  SOL:     { id: 'solana',                symbol: 'SOL',     decimals: 9,  type: 'volatile' },
  BONK:    { id: 'bonk',                  symbol: 'BONK',    decimals: 5,  type: 'volatile' },
  WIF:     { id: 'dogwifcoin',            symbol: 'WIF',     decimals: 6,  type: 'volatile' },
  JUP:     { id: 'jupiter-exchange-solana',symbol: 'JUP',    decimals: 6,  type: 'volatile' },
  PYTH:    { id: 'pyth-network',          symbol: 'PYTH',    decimals: 6,  type: 'volatile' },
  RAY:     { id: 'raydium',               symbol: 'RAY',     decimals: 6,  type: 'volatile' },
  ORCA:    { id: 'orca',                  symbol: 'ORCA',    decimals: 6,  type: 'volatile' },
  JTO:     { id: 'jito-governance-token', symbol: 'JTO',     decimals: 9,  type: 'volatile' },
  POPCAT:  { id: 'popcat',                symbol: 'POPCAT',  decimals: 9,  type: 'volatile' },
  BOME:    { id: 'book-of-meme',          symbol: 'BOME',    decimals: 6,  type: 'volatile' },
  MEW:     { id: 'cat-in-a-dogs-world',   symbol: 'MEW',     decimals: 5,  type: 'volatile' },
  SLERF:   { id: 'slerf',                 symbol: 'SLERF',   decimals: 9,  type: 'volatile' },
  SAMO:    { id: 'samoyedcoin',           symbol: 'SAMO',    decimals: 9,  type: 'volatile' },
  MNGO:    { id: 'mango-markets',         symbol: 'MNGO',    decimals: 6,  type: 'volatile' },
  RENDER:  { id: 'render-token',          symbol: 'RENDER',  decimals: 8,  type: 'volatile' },
  HNT:     { id: 'helium',                symbol: 'HNT',     decimals: 8,  type: 'volatile' },
  MOBILE:  { id: 'helium-mobile',         symbol: 'MOBILE',  decimals: 6,  type: 'volatile' },
  IOT:     { id: 'helium-iot',            symbol: 'IOT',     decimals: 6,  type: 'volatile' },
  GMT:     { id: 'stepn',                 symbol: 'GMT',     decimals: 8,  type: 'volatile' },
  GST:     { id: 'green-satoshi-token',   symbol: 'GST',     decimals: 9,  type: 'volatile' },
  DRIFT:   { id: 'drift-protocol',        symbol: 'DRIFT',   decimals: 6,  type: 'volatile' },
  ZEUS:    { id: 'zeus-network',          symbol: 'ZEUS',    decimals: 6,  type: 'volatile' },
  KMNO:    { id: 'kamino',                symbol: 'KMNO',    decimals: 6,  type: 'volatile' },
  MSOL:    { id: 'msol',                  symbol: 'mSOL',    decimals: 9,  type: 'volatile' },
  JSOL:    { id: 'jpool-staked-sol',      symbol: 'jSOL',    decimals: 9,  type: 'volatile' },
  STSOL:   { id: 'lido-staked-sol',       symbol: 'stSOL',   decimals: 9,  type: 'volatile' },
  BSOL:    { id: 'blazestake-staked-sol', symbol: 'bSOL',    decimals: 9,  type: 'volatile' },
  W:       { id: 'wormhole',              symbol: 'W',       decimals: 6,  type: 'volatile' },
  TNSR:    { id: 'tensor',                symbol: 'TNSR',    decimals: 9,  type: 'volatile' },
  PONKE:   { id: 'ponke',                 symbol: 'PONKE',   decimals: 9,  type: 'volatile' },
};

// Pairs config - base/quote
const PAIRS = [
  // === STABLE PAIRS ===
  { id: 'USDC-USDT',  base: 'USDC', quote: 'USDT',  type: 'stable',   feeTiers: [0.01, 0.05],       binSteps: [1, 2]       },
  { id: 'USDC-DAI',   base: 'USDC', quote: 'DAI',   type: 'stable',   feeTiers: [0.01, 0.05],       binSteps: [1, 2]       },
  { id: 'USDC-PYUSD', base: 'USDC', quote: 'PYUSD', type: 'stable',   feeTiers: [0.01, 0.05],       binSteps: [1, 2]       },
  { id: 'USDC-FRAX',  base: 'USDC', quote: 'FRAX',  type: 'stable',   feeTiers: [0.01, 0.05],       binSteps: [1, 2]       },
  { id: 'USDC-USDS',  base: 'USDC', quote: 'USDS',  type: 'stable',   feeTiers: [0.01, 0.05],       binSteps: [1, 2]       },
  { id: 'USDT-DAI',   base: 'USDT', quote: 'DAI',   type: 'stable',   feeTiers: [0.01, 0.05],       binSteps: [1, 2]       },
  { id: 'USDT-FRAX',  base: 'USDT', quote: 'FRAX',  type: 'stable',   feeTiers: [0.01, 0.05],       binSteps: [1, 2]       },
  { id: 'USDT-USDS',  base: 'USDT', quote: 'USDS',  type: 'stable',   feeTiers: [0.01, 0.05],       binSteps: [1, 2]       },
  { id: 'DAI-FRAX',   base: 'DAI',  quote: 'FRAX',  type: 'stable',   feeTiers: [0.01, 0.05],       binSteps: [1, 2]       },
  { id: 'TUSD-USDC',  base: 'TUSD', quote: 'USDC',  type: 'stable',   feeTiers: [0.01, 0.05],       binSteps: [1, 2]       },

  // === VOLATILE PAIRS ===
  { id: 'SOL-USDC',   base: 'SOL',    quote: 'USDC', type: 'volatile', feeTiers: [0.05, 0.3, 1],    binSteps: [5, 10, 25]  },
  { id: 'BONK-USDC',  base: 'BONK',   quote: 'USDC', type: 'volatile', feeTiers: [0.3, 1],          binSteps: [10, 25, 50] },
  { id: 'WIF-USDC',   base: 'WIF',    quote: 'USDC', type: 'volatile', feeTiers: [0.3, 1],          binSteps: [10, 25]     },
  { id: 'JUP-USDC',   base: 'JUP',    quote: 'USDC', type: 'volatile', feeTiers: [0.05, 0.3, 1],    binSteps: [5, 10, 25]  },
  { id: 'PYTH-USDC',  base: 'PYTH',   quote: 'USDC', type: 'volatile', feeTiers: [0.05, 0.3, 1],    binSteps: [5, 10, 25]  },
  { id: 'RAY-USDC',   base: 'RAY',    quote: 'USDC', type: 'volatile', feeTiers: [0.05, 0.3, 1],    binSteps: [5, 10, 25]  },
  { id: 'ORCA-USDC',  base: 'ORCA',   quote: 'USDC', type: 'volatile', feeTiers: [0.05, 0.3, 1],    binSteps: [5, 10, 25]  },
  { id: 'JTO-USDC',   base: 'JTO',    quote: 'USDC', type: 'volatile', feeTiers: [0.3, 1],          binSteps: [10, 25]     },
  { id: 'POPCAT-USDC',base: 'POPCAT', quote: 'USDC', type: 'volatile', feeTiers: [0.3, 1],          binSteps: [25, 50]     },
  { id: 'BOME-USDC',  base: 'BOME',   quote: 'USDC', type: 'volatile', feeTiers: [0.3, 1],          binSteps: [25, 50]     },
  { id: 'MEW-USDC',   base: 'MEW',    quote: 'USDC', type: 'volatile', feeTiers: [0.3, 1],          binSteps: [25, 50]     },
  { id: 'SLERF-USDC', base: 'SLERF',  quote: 'USDC', type: 'volatile', feeTiers: [0.3, 1],          binSteps: [25, 50]     },
  { id: 'SAMO-USDC',  base: 'SAMO',   quote: 'USDC', type: 'volatile', feeTiers: [0.3, 1],          binSteps: [10, 25]     },
  { id: 'RENDER-USDC',base: 'RENDER', quote: 'USDC', type: 'volatile', feeTiers: [0.05, 0.3, 1],    binSteps: [5, 10, 25]  },
  { id: 'HNT-USDC',   base: 'HNT',    quote: 'USDC', type: 'volatile', feeTiers: [0.05, 0.3, 1],    binSteps: [5, 10, 25]  },
  { id: 'MOBILE-USDC',base: 'MOBILE', quote: 'USDC', type: 'volatile', feeTiers: [0.3, 1],          binSteps: [10, 25]     },
  { id: 'IOT-USDC',   base: 'IOT',    quote: 'USDC', type: 'volatile', feeTiers: [0.3, 1],          binSteps: [10, 25]     },
  { id: 'GMT-USDC',   base: 'GMT',    quote: 'USDC', type: 'volatile', feeTiers: [0.3, 1],          binSteps: [10, 25]     },
  { id: 'DRIFT-USDC', base: 'DRIFT',  quote: 'USDC', type: 'volatile', feeTiers: [0.3, 1],          binSteps: [10, 25]     },
  { id: 'ZEUS-USDC',  base: 'ZEUS',   quote: 'USDC', type: 'volatile', feeTiers: [0.3, 1],          binSteps: [10, 25]     },
  { id: 'KMNO-USDC',  base: 'KMNO',   quote: 'USDC', type: 'volatile', feeTiers: [0.3, 1],          binSteps: [10, 25]     },
  { id: 'W-USDC',     base: 'W',      quote: 'USDC', type: 'volatile', feeTiers: [0.3, 1],          binSteps: [10, 25]     },
  { id: 'TNSR-USDC',  base: 'TNSR',   quote: 'USDC', type: 'volatile', feeTiers: [0.3, 1],          binSteps: [10, 25]     },
  { id: 'PONKE-USDC', base: 'PONKE',  quote: 'USDC', type: 'volatile', feeTiers: [0.3, 1],          binSteps: [25, 50]     },
  { id: 'MSOL-SOL',   base: 'MSOL',   quote: 'SOL',  type: 'volatile', feeTiers: [0.05, 0.3],       binSteps: [1, 5]       },
  { id: 'JSOL-SOL',   base: 'JSOL',   quote: 'SOL',  type: 'volatile', feeTiers: [0.05, 0.3],       binSteps: [1, 5]       },
  { id: 'BSOL-SOL',   base: 'BSOL',   quote: 'SOL',  type: 'volatile', feeTiers: [0.05, 0.3],       binSteps: [1, 5]       },
  { id: 'MNGO-USDC',  base: 'MNGO',   quote: 'USDC', type: 'volatile', feeTiers: [0.3, 1],          binSteps: [10, 25]     },
  { id: 'BONK-SOL',   base: 'BONK',   quote: 'SOL',  type: 'volatile', feeTiers: [0.3, 1],          binSteps: [25, 50]     },
  { id: 'WIF-SOL',    base: 'WIF',    quote: 'SOL',  type: 'volatile', feeTiers: [0.3, 1],          binSteps: [10, 25]     },
  { id: 'JUP-SOL',    base: 'JUP',    quote: 'SOL',  type: 'volatile', feeTiers: [0.05, 0.3],       binSteps: [5, 10]      },
  { id: 'RAY-SOL',    base: 'RAY',    quote: 'SOL',  type: 'volatile', feeTiers: [0.05, 0.3],       binSteps: [5, 10]      },
];

// Faucet amounts per token
const FAUCET_AMOUNTS = {
  USDC: 10000, USDT: 10000, DAI: 10000, PYUSD: 10000,
  FRAX: 10000, USDS: 10000, TUSD: 10000, BUSD: 10000,
  GUSD: 10000, USDP: 10000,
  SOL: 100, BONK: 10000000, WIF: 1000, JUP: 5000,
  PYTH: 5000, RAY: 500, ORCA: 500, JTO: 500,
  POPCAT: 1000, BOME: 5000000, MEW: 5000000, SLERF: 500,
  SAMO: 100000, MNGO: 10000, RENDER: 500, HNT: 200,
  MOBILE: 1000000, IOT: 1000000, GMT: 1000, GST: 1000,
  DRIFT: 5000, ZEUS: 5000, KMNO: 5000, MSOL: 50,
  JSOL: 50, STSOL: 50, BSOL: 50, W: 10000,
  TNSR: 5000, PONKE: 10000,
};
